#!/bin/bash

#creates a AlmaLinux 8 kickstart based template
#This script requires a working metalcloud-cli and jq tools.

#Note this will delete the existing template instead of updating it.

if [ "$#" -ne 2 ]; then
    echo "syntax: $0 <template-id> <os-version (eg: 8.)>"
    exit
fi

TEMPLATE_VERSION="$2" 
TEMPLATE_DISPLAY_NAME="AlmaLinux $TEMPLATE_VERSION"
TEMPLATE_DESCRIPTION="$TEMPLATE_DISPLAY_NAME ISCSI legacy_boot"
TEMPLATE_LABEL=$1
TEMPLATE_ROOT=".tftp/boot/images/AlmaLinux-$TEMPLATE_VERSION"


SOURCES="./$TEMPLATE_VERSION"

MC="metalcloud-cli"

DATACENTER_NAME="$METALCLOUD_DATACENTER"
REPO_URL=$(metalcloud-cli datacenter get --id "$DATACENTER_NAME" --show-config --format json | jq ".[0].CONFIG | fromjson |.repoURLRoot" -r)
TEMPLATE_BASE=$REPO_URL/$TEMPLATE_ROOT
TEMPLATE_IPXE_BASE="$REPO_URL/.tftp/boot/ipxe"

# * It's ok to fail with _template <template_label> not found_ if an OS-template with this label doesn't yet exist
if $MC os-template get --id "$TEMPLATE_LABEL" --format json; then
    # * The delete operation, it's ok to fail, when the OS-template <template_label> it's used by an active instance
    if $MC os-template delete --id "$TEMPLATE_LABEL" --autoconfirm; then
        OS_TEMPLATE_COMMAND=create
        OS_TEMPLATE_FLAG=label
    else
        OS_TEMPLATE_COMMAND=update
        OS_TEMPLATE_FLAG=id
    fi
else
    OS_TEMPLATE_COMMAND=create
    OS_TEMPLATE_FLAG=label
fi

#create the template
$MC os-template $OS_TEMPLATE_COMMAND \
--$OS_TEMPLATE_FLAG "$TEMPLATE_LABEL" \
--display-name "$TEMPLATE_DISPLAY_NAME" \
--description "$TEMPLATE_DESCRIPTION" \
--boot-type legacy_only \
--os-architecture "x86_64" \
--os-type "AlmaLinux" \
--os-version "$TEMPLATE_VERSION" \
--use-autogenerated-initial-password \
--initial-user "root" \
--initial-ssh-port 22 \
--boot-methods-supported "pxe_iscsi"

#first param is asset name, 
#second param is asset url relative to $TEMPLATE_IPXE_BASE 
#third param is usage
function addIPXEBinaryURLAsset {
    $MC asset create --url "$TEMPLATE_IPXE_BASE/$2" --filename "$1-$TEMPLATE_LABEL" \
    --template-id "$TEMPLATE_LABEL" --mime "application/octet-stream" --path "/$1" \
    --delete-if-exists --usage "$3" --return-id
}

#first param is asset name, 
#second param is asset url relative to $TEMPLATE_BASE 
#third param is usage
function addBinaryURLAsset {
    $MC asset create --url "$TEMPLATE_BASE/$2" --filename "$1-$TEMPLATE_LABEL" \
    --template-id "$TEMPLATE_LABEL" --mime "application/octet-stream" --path "/$1" \
    --delete-if-exists --usage "$3" --return-id
}

#firt param is file name on disk
#second param is path in tftp/http
#third param is params accepted
function addFileAsset {
    $MC asset create --filename "$1-$TEMPLATE_LABEL" --template-id "$TEMPLATE_LABEL" \
    --mime "text/plain" --path "$2" --delete-if-exists --pipe < "$SOURCES/$1"
}

TEMPLATE_REGULAR_BOOTLOADER_ASSET=$(addIPXEBinaryURLAsset "undionly.kpxe" "undionly.kpxe" "bootloader")

TEMPLATE_INSTALL_BOOTLOADER_ASSET=$TEMPLATE_REGULAR_BOOTLOADER_ASSET

#set the undionly.kpxe bootloader as the template's default bootloader
metalcloud-cli os-template update --id "$TEMPLATE_LABEL" --install-bootloader-asset "$TEMPLATE_INSTALL_BOOTLOADER_ASSET" --os-boot-bootloader-asset "$TEMPLATE_REGULAR_BOOTLOADER_ASSET"

#add ipxe config file
addFileAsset "almalinux-install.ipxe" "/ipxe_config_install"
addFileAsset "almalinux-regular-boot.ipxe" "/ipxe_config_os_boot"

#add vmlinuz
addBinaryURLAsset 'vmlinuz' 'vmlinuz'

#add initrd.img
addBinaryURLAsset 'initrd.img' 'initrd.img'

#add kickstart file ks-iscsi.cfg
addFileAsset 'ks-iscsi.cfg' '/ks.cfg'

#add snmpd.conf
addFileAsset 'snmpd.conf' '/snmpd.conf'
